apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: master-channel
spec:
  config:
    min.insync.replicas: "2"
    retention.ms: "7200000"
    segment.bytes: "1073741824"
  partitions: 3
  replicas: 3
  topicName: master-channel
