apiVersion: v1
kind: Service
metadata:
  annotations:
    name: kafka-camel-router-service
spec:
  ports:
    - name: rsocket
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080